// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddProject(arg1:string):Promise<main.ProjectRegistryEntry>;

export function CreateProject(arg1:string,arg2:string,arg3:string):Promise<main.ProjectMeta>;

export function EndMeeting(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function GetOrCreateActiveMeeting(arg1:string):Promise<main.Meeting>;

export function GetProjectMeta(arg1:string):Promise<main.ProjectMeta>;

export function GetProjects():Promise<Array<main.ProjectRegistryEntry>>;

export function GetRoleTemplates():Promise<Array<main.RoleTemplate>>;

export function GetTeamRoles(arg1:string):Promise<Array<string>>;

export function InitProjectTeam(arg1:string,arg2:Array<string>):Promise<boolean>;

export function ListMeetings(arg1:string):Promise<Array<main.MeetingSummary>>;

export function LoadMeeting(arg1:string,arg2:string):Promise<main.Meeting>;

export function RemoveProject(arg1:string):Promise<boolean>;

export function SaveMeetingMessage(arg1:string,arg2:string,arg3:main.Message):Promise<boolean>;
