// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function CreateProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3);
}

export function CreateProjectWithRoles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProjectWithRoles'](arg1, arg2, arg3, arg4);
}

export function EndActiveMeeting(arg1) {
  return window['go']['main']['App']['EndActiveMeeting'](arg1);
}

export function EndMeeting(arg1, arg2, arg3) {
  return window['go']['main']['App']['EndMeeting'](arg1, arg2, arg3);
}

export function GetActiveMeeting(arg1) {
  return window['go']['main']['App']['GetActiveMeeting'](arg1);
}

export function GetProjectMeta(arg1) {
  return window['go']['main']['App']['GetProjectMeta'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRoleTemplates() {
  return window['go']['main']['App']['GetRoleTemplates']();
}

export function GetTeamRoles(arg1) {
  return window['go']['main']['App']['GetTeamRoles'](arg1);
}

export function InitProjectTeam(arg1, arg2) {
  return window['go']['main']['App']['InitProjectTeam'](arg1, arg2);
}

export function ListMeetings(arg1) {
  return window['go']['main']['App']['ListMeetings'](arg1);
}

export function LoadMeeting(arg1, arg2) {
  return window['go']['main']['App']['LoadMeeting'](arg1, arg2);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SaveMeetingMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMeetingMessage'](arg1, arg2, arg3);
}

export function StartMeeting(arg1, arg2) {
  return window['go']['main']['App']['StartMeeting'](arg1, arg2);
}
